<?xml version='1.0'?>

<robot name="myrobot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!--wheels -->
  <xacro:property name="drive_wheel_diameter" value="0.1811"/>
  <xacro:property name="drive_wheel_width" value="0.0381"/>
  <xacro:property name="drive_wheel_mass" value="2.5"/>

  <xacro:property name="caster_wheel_diameter" value="0.1811"/>
  <xacro:property name="caster_wheel_width" value="0.0508"/>
  <xacro:property name="caster_wheel_mass" value="3.7"/>


  <!--chassis -->
  <xacro:property name="chassis_length" value="0.50"/>
  <xacro:property name="chassis_width" value="0.25"/>
  <xacro:property name="chassis_height" value="0.01"/>
  <xacro:property name="chassis_mass" value="25"/>
  <xacro:property name="vehicle_clearance" value="0.25"/>


  <!--camera -->
  <xacro:property name="cameraSize" value="0.01"/>
  <xacro:property name="cameraMass" value="0.03"/>
  <xacro:property name="camera_mount_height" value="0.5"/>
  <xacro:property name="camera_mount_width" value="0.05"/>
  <xacro:property name="camera_mount_length" value="0.05"/>
  <xacro:property name="camera_mount_mass" value="0.05"/>





  <xacro:include filename="$(find boilerbot_description_integ)/urdf/mybot.gazebo" />
  <xacro:include filename="$(find boilerbot_description_integ)/urdf/materials.xacro" />
  <xacro:include filename="$(find boilerbot_description_integ)/urdf/macros.xacro" />



  <!-- Chassis Link -->
  <link name='base_link'>
    <pose>0 0 0 0 0 0</pose>

  </link>



  <link name='chassis'>
    <pose>0 0 0 0 0 0</pose>

    <inertial>
      <mass value="${chassis_mass}"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="${2 / 5 * chassis_mass * 1 ** 2}" ixy="0" ixz="0"
          iyy="${2 / 5 * chassis_mass * 1 ** 2}" iyz="0"
          izz="${2 / 5 * chassis_mass * 1 ** 2}"
      />
    </inertial>

    <collision name='collision'>
      <geometry>
        <mesh filename="package://boilerbot_description_integ/meshes/bodyNoWheels.dae"/>
      </geometry>
    </collision>

    <visual name='chassis_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 -1.5707"/>
      <geometry>
        <mesh filename="package://boilerbot_description_integ/meshes/bodyNoWheels.dae"/>
      </geometry>
    </visual>
  </link>

  <!-- Payload -->
  <!--<link name="payload">-->


  <!-- Left Castor Wheel Link -->

  <link name="left_castor_wheel">
    <collision name='left_caster_collision'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <cylinder radius="${caster_wheel_diameter/2}" length="${caster_wheel_width}"/>
      </geometry>
    </collision>

    <visual name="left_caster_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${caster_wheel_diameter/2}" length="${caster_wheel_width}"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="${caster_wheel_mass}"/>
      <cylinder_inertia m="${caster_wheel_mass}" r="${caster_wheel_diameter/2}" h="${drive_wheel_width}"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>


  <!-- Right Castor Wheel Link -->

  <link name="right_castor_wheel">
    <collision name='right_caster_collision'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${caster_wheel_diameter/2}" length="${caster_wheel_width}"/>
      </geometry>
    </collision>

    <visual name="right_caster_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${caster_wheel_diameter/2}" length="${caster_wheel_width}"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="${caster_wheel_mass}"/>
      <cylinder_inertia m="${caster_wheel_mass}" r="${caster_wheel_diameter/2}" h="${caster_wheel_width}"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>


  <!-- Left Drive Wheel Link -->

  <link name="left_drive_wheel">
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${drive_wheel_diameter/2}" length="${drive_wheel_width}"/>
      </geometry>
    </collision>
    <visual name="left_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${drive_wheel_diameter/2}" length="${drive_wheel_width}"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="${drive_wheel_mass}"/>
      <cylinder_inertia m="${drive_wheel_mass}" r="${drive_wheel_diameter/2}" h="${drive_wheel_width}"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>


  <!-- Right Drive Wheel Link -->

  <link name="right_drive_wheel">
    <!--origin xyz="0.1 -0.13 0.1" rpy="0 1.5707 1.5707"/-->
    <collision name="collision">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${drive_wheel_diameter/2}" length="${drive_wheel_width}"/>
      </geometry>
    </collision>
    <visual name="right_wheel_visual">
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <geometry>
        <cylinder radius="${drive_wheel_diameter/2}" length="${drive_wheel_width}"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
      <mass value="${drive_wheel_mass}"/>
      <cylinder_inertia m="${drive_wheel_mass}" r="${drive_wheel_diameter/2}" h="${drive_wheel_width}"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <!-- Base Link Chassis joint -->
  <joint type="fixed" name="base_link_chassis">
    <origin xyz="0 0 -0.1" rpy="0 0 0"/>
    <child link="chassis"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Left Drive wheel joint -->

  <joint type="continuous" name="left_drive_hinge">
    <origin xyz="0 0.31 0" rpy="0 0 0"/>
    <child link="left_drive_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  <!-- Right Drive Wheel Joint -->

  <joint type="continuous" name="right_drive_hinge">
    <origin xyz="0 -0.31 0" rpy="0 0 0"/>
    <child link="right_drive_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  <!-- Left Castor Wheel Joint -->

  <joint type="continuous" name="left_castor_hinge">
    <origin xyz="-0.53 0.13 0" rpy="0 0 0"/>
    <child link="left_castor_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  <!-- Right Castor Wheel Joint -->

  <joint type="continuous" name="right_castor_hinge">
    <origin xyz="-0.53 -0.13 0" rpy="0 0 0"/>
    <child link="right_castor_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>




  <!-- Camera -->

  <link name="camera">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${cameraSize} ${cameraSize} ${cameraSize}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <inertial>
      <mass value="${cameraMass}" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <box_inertia m="${cameraMass}" x="${cameraSize}" y="${cameraSize}" z="${cameraSize}" />
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>


  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="-0.04 0 0.95" rpy="0 0.5 0"/>
    <parent link="base_link"/>
    <child link="camera"/>
  </joint>


  <!-- Hokuyo Laser -->
  <link name="hokuyo">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://boilerbot_description_integ/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0.25 0 .420" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="hokuyo"/>
  </joint>



</robot>
