obstacle_range: 6.0
raytrace_range: 8.5
footprint: [[-0.55, -0.31], [-0.55, 0.31], [0.25, -0.31], [0.25, 0.31]]   #right_wheel = 0,-0.31, left_wheel=0,0.31, right_castor_wheel=-0.53, -0.13, left_castor_wheel=-0.53, 0.13, hokuyo=0.25,0
#robot_radius: ir_of_robot
#robot_radius: 0.5 # distance a circular robot should be clear of the obstacle
inflation_radius: 1.0

observation_sources: laser_scan_sensor #point_cloud_sensor

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /mybot/laser/scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
