# static_map - True if using existing map

global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  resolution: 0.05
  static_map: false
  width: 100
  height: 100  
  origin_x: -50
  origin_y: -50
  rolling_window: false


  
