# static_map - True if using existing map

global_costmap:
  global_frame: odom
  robot_base_frame: chassis
  update_frequency: 2.5
  publish_frequency: 2.5
  resolution: 0.05
  static_map: false
  rolling_window: false
  width: 100.0
  height: 100.0
  origin_x: -50
  origin_y: -50
  inflation_radius: 1.0
