TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.01
  max_vel_theta: 1.5
  min_in_place_vel_theta: 0.01

  acc_lim_theta: 1.5
  acc_lim_x: 0.5
  acc_lim_y: 0.5


  holonomic_robot: false
  meter_scoring: true
  #heading_lookahead: 0.5  #How far to look ahead in meters when scoring different in-place-rotation trajectories
  #heading_scoring: false  #Whether to score based on the robot's heading to the path or its distance from the path. default false
  #heading_scoring_timestep: 1.0   #How far to look ahead in time in seconds along the simulated trajectory when using heading scoring (double, default: 0.8)
