TrajectoryPlannerROS:
  max_vel_x: 0.6
  min_vel_x: 0.01
  max_vel_theta: 1.5
  min_in_place_vel_theta: 0.01

  acc_lim_theta: 1.5
  acc_lim_x: 0.5
  acc_lim_y: 0
  path_distance_bias: 0.6
  goal_distance_bias: 0.8
  occdist_scale: 0.03
  dwa: true


  holonomic_robot: false
  meter_scoring: true

  #sim_time: 1.0
  #sim_granularity: 0.025
  #angular_sim_granularity: 0.02
  vx_samples: 10
  vtheta_samples: 20
  #controller_frequency: 10
  #heading_lookahead: 0.5  #How far to look ahead in meters when scoring different in-place-rotation trajectories
  #heading_scoring: false  #Whether to score based on the robot's heading to the path or its distance from the path. default false
  #heading_scoring_timestep: 1.0   #How far to look ahead in time in seconds along the simulated trajectory when using heading scoring (double, default: 0.8)
