<?xml version="1.0"?>

<robot name="igvc_platform" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- include other xacro files to use their macros -->
  <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>

  <!-- passed in parameters -->
  <xacro:arg name="gpu" default="false" />

  <!-- constants -->
  <xacro:property name="M_PI" value="3.1415926535897931" />

  <xacro:property name="chassis_mass" value="32" />

  <!-- wheels -->
  <xacro:property name="drive_tire_diameter" value="0.305"/>
  <xacro:property name="drive_tire_width" value="0.0762"/>
  <!-- TODO set proper mass values -->
  <xacro:property name="drive_wheel_mass" value="5.0"/>

  <xacro:property name="wheelbase" value="0.714333"/>

  <!-- wheel acuator limits -->
  <xacro:property name="drive_wheel_eff_limit" value="8"/>
  <xacro:property name="drive_wheel_vel_limit" value="10"/>

  <!-- drive shock params-->
  <!-- how far the drive wheel shock can move (m)-->
  <xacro:property name="drive_wheel_travel" value="0.1"/>
  <xacro:property name="drive_shock_eff_limit" value="500.0"/>
  <xacro:property name="drive_shock_vel_limit" value="0.1"/>


  <!-- gives small geometry so it show up in rviz -->
  <xacro:macro name="null_link">
    <inertial>
      <mass value="0.001"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
    <visual>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
    </visual>
  </xacro:macro>



  <!-- base of the robot, should be ground level directly below center points of wheels -->
  <link name="base_link">
  <xacro:null_link/>
  </link>
  <gazebo reference="base_link">
  <material>Gazebo/Grey</material>
  </gazebo>

  <link name="base_footprint">
  <xacro:null_link/>
  </link>
  <gazebo reference="base_footprint">
  <material>Gazebo/Grey</material>
  </gazebo>

  <joint name="base_footprint_to_base_link" type="fixed">
  <parent link="base_footprint"/>
  <child link="base_link"/>
  <origin xyz="0.0 0.0 ${drive_tire_diameter / 2}" rpy="0 0 0"/>
  <axis xyz="0 0 0"/>
  </joint>


  <link name="body">
       <inertial>
           <mass value="${chassis_mass}" />
           <origin xyz="0 0 0" rpy="0 0 0"/>
           <!-- approximate the intertial matrix as a sphere -->
           <inertia  ixx="${2 / 5 * chassis_mass * 1 ** 2}" ixy="0.0" ixz="0.0"
                     iyy="${2 / 5 * chassis_mass * 1 ** 2}" iyz="0.0"
                     izz="${2 / 5 * chassis_mass * 1 ** 2}" />
       </inertial>
       <visual>
           <geometry>
               <mesh filename="package://igvc_description/urdf/meshes/jessi_simple.dae"/>
           </geometry>
       </visual>
       <collision>
           <geometry>
               <mesh filename="package://igvc_description/urdf/meshes/jessi_simple.dae"/>
           </geometry>
       </collision>
   </link>

   <joint name="base_link_to_body" type="fixed">
      <parent link="base_link"/>
      <child link="body"/>
      <origin xyz="0.2 0.0 0.17" rpy="0 0 ${M_PI / 2}"/>
      <axis xyz="0 0 0"/>
    </joint>


  

</robot>
